/* vim:expandtab:shiftwidth=2:tabstop=2:smarttab:
 * Copyright 2014 Hewlett-Packard Development Company, L.P.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may obtain 
 * a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 */

#pragma once

#include "config.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ATTACHSQL_DEFAULT_PORT 3306
#define ATTACHSQL_ERROR_BUFFER_SIZE 255
#define ATTACHSQL_MAX_SERVER_VERSION_LEN 32
#define ATTACHSQL_MAX_USER_SIZE 16
#define ATTACHSQL_MAX_SCHEMA_SIZE 64
#define ATTACHSQL_MAX_TABLE_SIZE 64
#define ATTACHSQL_MAX_COLUMN_SIZE 64
#define ATTACHSQL_MAX_DEFAULT_VALUE_SIZE 2048
#define ATTACHSQL_MAX_MESSAGE_LEN 2048
#define ATTACHSQL_WRITE_BUFFER_SIZE 1024
#define ATTACHSQL_MINIMUM_COMPRESS_SIZE 50
#define ATTACHSQL_STMT_EXEC_DEFAULT_SIZE 16*1024
#define ATTACHSQL_DEFAULT_PACKET_QUEUE_SIZE 64

#define ATTACHSQL_STMT_PARAM_UNSIGNED_BIT 0x8000

enum attachsql_con_protocol_t
{
  ATTACHSQL_CON_PROTOCOL_UNKNOWN,
  ATTACHSQL_CON_PROTOCOL_UDS,
  ATTACHSQL_CON_PROTOCOL_TCP
};

enum attachsql_con_options_t
{
  ATTACHSQL_CON_OPTION_POLLING,
  ATTACHSQL_CON_OPTION_RAW_SCRAMBLE,
  ATTACHSQL_CON_OPTION_FOUND_ROWS,
  ATTACHSQL_CON_OPTION_INTERACTIVE,
  ATTACHSQL_CON_OPTION_MULTI_STATEMENTS,
  ATTACHSQL_CON_OPTION_AUTH_PLUGIN,
  ATTACHSQL_CON_OPTION_PROTOCOL_TCP,
  ATTACHSQL_CON_OPTION_PROTOCOL_UDS
};

enum attachsql_con_status_t
{
  ATTACHSQL_CON_STATUS_PARAMETER_ERROR,
  ATTACHSQL_CON_STATUS_NOT_CONNECTED,
  ATTACHSQL_CON_STATUS_CONNECTING,
  ATTACHSQL_CON_STATUS_CONNECT_FAILED,
  ATTACHSQL_CON_STATUS_BUSY,
  ATTACHSQL_CON_STATUS_IDLE,
  ATTACHSQL_CON_STATUS_SSL_ERROR,
  ATTACHSQL_CON_STATUS_NET_ERROR
};

enum attachsql_packet_type_t
{
  ATTACHSQL_PACKET_TYPE_NONE,
  ATTACHSQL_PACKET_TYPE_HANDSHAKE,
  ATTACHSQL_PACKET_TYPE_HANDSHAKE_SSL,
  ATTACHSQL_PACKET_TYPE_RESPONSE,
  ATTACHSQL_PACKET_TYPE_PREPARE_RESPONSE,
  ATTACHSQL_PACKET_TYPE_PREPARE_PARAMETER,
  ATTACHSQL_PACKET_TYPE_PREPARE_COLUMN,
  ATTACHSQL_PACKET_TYPE_COLUMN,
  ATTACHSQL_PACKET_TYPE_ROW,
  ATTACHSQL_PACKET_TYPE_STMT_ROW
};

enum attachsql_capabilities_t
{
  ATTACHSQL_CAPABILITY_NONE=               0,
  ATTACHSQL_CAPABILITY_LONG_PASSWORD=      (1 << 0),
  ATTACHSQL_CAPABILITY_FOUND_ROWS=         (1 << 1),
  ATTACHSQL_CAPABILITY_LONG_FLAG=          (1 << 2),
  ATTACHSQL_CAPABILITY_CONNECT_WITH_DB=    (1 << 3),
  ATTACHSQL_CAPABILITY_NO_SCHEMA=          (1 << 4),
  ATTACHSQL_CAPABILITY_COMPRESS=           (1 << 5),
  ATTACHSQL_CAPABILITY_ODBC=               (1 << 6),
  ATTACHSQL_CAPABILITY_LOCAL_FILES=        (1 << 7),
  ATTACHSQL_CAPABILITY_IGNORE_SPACE=       (1 << 8),
  ATTACHSQL_CAPABILITY_PROTOCOL_41=        (1 << 9),
  ATTACHSQL_CAPABILITY_INTERACTIVE=        (1 << 10),
  ATTACHSQL_CAPABILITY_SSL=                (1 << 11),
  ATTACHSQL_CAPABILITY_IGNORE_SIGPIPE=     (1 << 12),
  ATTACHSQL_CAPABILITY_TRANSACTIONS=       (1 << 13),
  ATTACHSQL_CAPABILITY_RESERVED=           (1 << 14),
  ATTACHSQL_CAPABILITY_SERCURE_CONNECTION= (1 << 15),
  ATTACHSQL_CAPABILITY_MULTI_STATEMENTS=   (1 << 16),
  ATTACHSQL_CAPABILITY_MULTI_RESULTS=      (1 << 17),
  ATTACHSQL_CAPABILITY_PLUGIN_AUTH=        (1 << 19),
  ATTACHSQL_CAPABILITY_CLIENT=            (ATTACHSQL_CAPABILITY_LONG_PASSWORD    |
                                        ATTACHSQL_CAPABILITY_FOUND_ROWS       |
                                        ATTACHSQL_CAPABILITY_LONG_FLAG        |
                                        ATTACHSQL_CAPABILITY_CONNECT_WITH_DB  |
                                        ATTACHSQL_CAPABILITY_PLUGIN_AUTH      |
                                        ATTACHSQL_CAPABILITY_TRANSACTIONS     |
                                        ATTACHSQL_CAPABILITY_PROTOCOL_41      |
                                        ATTACHSQL_CAPABILITY_SERCURE_CONNECTION)
};


enum attachsql_command_status_t
{
  ATTACHSQL_COMMAND_STATUS_EOF,
  ATTACHSQL_COMMAND_STATUS_CONNECTED,
  ATTACHSQL_COMMAND_STATUS_SEND,
  ATTACHSQL_COMMAND_STATUS_SEND_FAILED,
  ATTACHSQL_COMMAND_STATUS_READ_RESPONSE,
  ATTACHSQL_COMMAND_STATUS_READ_COLUMN,
  ATTACHSQL_COMMAND_STATUS_READ_ROW,
  ATTACHSQL_COMMAND_STATUS_READ_FAILED,
  ATTACHSQL_COMMAND_STATUS_ROW_IN_BUFFER,
  ATTACHSQL_COMMAND_STATUS_READ_STMT_PARAM,
  ATTACHSQL_COMMAND_STATUS_READ_STMT_COLUMN,
  ATTACHSQL_COMMAND_STATUS_READ_STMT_ROW
};

enum attachsql_command_t
{
  ATTACHSQL_COMMAND_SLEEP=               0x00,
  ATTACHSQL_COMMAND_QUIT=                0x01,
  ATTACHSQL_COMMAND_INITDB=              0x02,
  ATTACHSQL_COMMAND_QUERY=               0x03,
  ATTACHSQL_COMMAND_FIELD_LIST=          0x04,
  ATTACHSQL_COMMAND_CREATE_DB=           0x05,
  ATTACHSQL_COMMAND_DROP_DB=             0x06,
  ATTACHSQL_COMMAND_REFRESH=             0x07,
  ATTACHSQL_COMMAND_SHUTDOWN=            0x08,
  ATTACHSQL_COMMAND_STATISTICS=          0x09,
  ATTACHSQL_COMMAND_PROCESS_INFO=        0x0a,
  ATTACHSQL_COMMAND_CONNECT=             0x0b,
  ATTACHSQL_COMMAND_PROCESS_KILL=        0x0c,
  ATTACHSQL_COMMAND_DEBUG=               0x0d,
  ATTACHSQL_COMMAND_PING=                0x0e,
  ATTACHSQL_COMMAND_TIME=                0x0f,
  ATTACHSQL_COMMAND_DELAYED_INSERT=      0x10,
  ATTACHSQL_COMMAND_CHANGE_USER=         0x11,
  ATTACHSQL_COMMAND_BINLOG_DUMP=         0x12,
  ATTACHSQL_COMMAND_TABLE_DUMP=          0x13,
  ATTACHSQL_COMMAND_CONNECT_OUT=         0x14, /* Internal (unused) */
  ATTACHSQL_COMMAND_REGISTER_SLAVE=      0x15,
  ATTACHSQL_COMMAND_STMT_PREPARE=        0x16,
  ATTACHSQL_COMMAND_STMT_EXECUTE=        0x17,
  ATTACHSQL_COMMAND_STMT_SEND_LONG_DATA= 0x18,
  ATTACHSQL_COMMAND_STMT_CLOSE=          0x19,
  ATTACHSQL_COMMAND_STMT_RESET=          0x1a,
  ATTACHSQL_COMMAND_SET_OPTION=          0x1b,
  ATTACHSQL_COMMAND_STMT_FETCH=          0x1c,
  ATTACHSQL_COMMAND_DAEMON=              0x1d,
  ATTACHSQL_COMMAND_BINLOG_DUMP_GTID=    0x1e,
  ATTACHSQL_COMMAND_RESET_CONNECTION=    0x1f
};

enum attachsql_server_status_t
{
  ATTACHSQL_SERVER_STATUS_NONE=                     0,
  ATTACHSQL_SERVER_STATUS_IN_TRANSACTION=           (1 << 0),
  ATTACHSQL_SERVER_STATUS_AUTOCOMMIT=               (1 << 1),
  // (1 << 2) unusued
  ATTACHSQL_SERVER_STATUS_MORE_RESULTS=             (1 << 3),
  ATTACHSQL_SERVER_STATUS_NO_GOOD_INDEX=            (1 << 4),
  ATTACHSQL_SERVER_STATUS_NO_INDEX=                 (1 << 5),
  ATTACHSQL_SERVER_STATUS_CURSOR_EXISTS=            (1 << 6),
  ATTACHSQL_SERVER_STATUS_LAST_ROW_SENT=            (1 << 7),
  ATTACHSQL_SERVER_STATUS_DB_DROPPED=               (1 << 8),
  ATTACHSQL_SERVER_STATUS_NO_BACKSLASH_ESCAPES=     (1 << 9),
  ATTACHSQL_SERVER_STATUS_METADATA_CHANGED=         (1 << 10),
  ATTACHSQL_SERVER_STATUS_QUERY_WAS_SLOW=           (1 << 11),
  ATTACHSQL_SERVER_STATUS_PS_OUT_PARAMS=            (1 << 12),
  ATTACHSQL_SERVER_STATUS_IN_TRANSACTION_READ_ONLY= (1 << 13)
};

enum attachsql_stmt_state_t
{
  ATTACHSQL_STMT_STATE_NONE,
  ATTACHSQL_STMT_STATE_PREPARED,
  ATTACHSQL_STMT_STATE_EXECUTED
};

enum attachsql_stmt_cursor_t
{
  ATTACHSQL_STMT_CURSOR_NONE=       0x00,
  ATTACHSQL_STMT_CURSOR_READ_ONLY=  0x01,
  ATTACHSQL_STMT_CURSOR_FOR_UPDATE= 0x02,
  ATTACHSQL_STMT_CURSOR_SCROLLABLE= 0x03
};
#ifdef __cplusplus
}
#endif

